inherit_gem:
  rubocop-basic: rubocop.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4.4
  Exclude:
    - Gemfile.lock
    - db/schema.rb
    - bin/*
    - config/environments/*
    - node_modules/**/*
    - log/**/*
    - tmp/**/*
    - vendor/**/*

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
