AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - Gemfile.lock
    - db/schema.rb
    - bin/*
    - config/environments/*
    - node_modules/**/*
    - log/**/*
    - tmp/**/*
    - vendor/**/*

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/ExpandPathArguments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Security/YAMLLoad:
  Enabled: false
