version: "3.9"

services:
  app:
    build:
      context: .
      target: build
    develop:
      watch:
        - action: rebuild
          path: ./Gemfile
        - action: rebuild
          path: ./Gemfile.lock
        - path: ./package.json
          action: rebuild
        - path: ./bun.lockb
          action: rebuild
        - action: sync
          path: ./
          target: /rails
    environment:
      DATABASE_URL: postgres://localhost
    ports:
      - "3000:3000"

  js:
    build:
      context: .
      target: local
    command: ["bun", build", "./app/packs/entrypoints/application.ts", "--outdir", "./app/assets/builds"]

  css:
    build:
      context: .
      target: local
    command: ["tailwindcss", "--input", "./app/packs/entrypoints/application.tailwind.css", "--output", "./app/assets/builds/application.css"]
