version: 2.1
orbs:
  browser-tools: circleci/browser-tools@2.4.2
  docker: circleci/docker@4.0.1
  node: circleci/node@7.2.1
  ruby: circleci/ruby@3.0.0
  qlty: qltysh/qlty-orb@0.1.2

executors:
  default:
    docker:
      - image: cimg/ruby:4.0.6-browsers
      - image: cimg/postgres:17.5
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      CI: on
      PGHOST: localhost

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages

jobs:
  containerize:
    executor:
      name: docker/machine
      dlc: true
    parameters:
      image:
        type: string
        default: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      tag:
        type: string
        default: << pipeline.git.revision >>`if [ '<< pipeline.git.branch >>' == 'main' ]; then echo ",latest"; fi`
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: << parameters.image >>
          tag: << parameters.tag >>
      - docker/push:
          image: << parameters.image >>
          tag: << parameters.tag >>
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            - run: curl $DEPLOY_URL

  brakeman:
    executor: default
    steps:
      - setup
      - run: bundle exec brakeman -z --format html --output tmp/brakeman.html
      - store_artifacts:
          path: tmp/brakeman.html
          destination: brakeman.html

  oxlint:
    executor: default
    steps:
      - setup
      - run: npm run lint

  oxfmt:
    executor: default
    steps:
      - setup
      - run: npm run fmt

  tsc:
    executor: default
    steps:
      - setup
      - run: npm run typecheck

  rubocop:
    executor: default
    steps:
      - setup
      - ruby/rubocop-check

  rspec:
    executor: default
    steps:
      - setup
      - browser-tools/install_chrome
      - browser-tools/install_chromedriver
      - run: dockerize -wait tcp://localhost:5432 -timeout 2m # Postgres
      - run: bin/rails db:test:prepare test:prepare
      - ruby/rspec-test
      - qlty/coverage_publish:
          files: ./coverage/.resultset.json

workflows:
  version: 2.1
  build:
    jobs:
      - brakeman
      - containerize
      - oxfmt
      - oxlint
      - rspec
      - rubocop
      - tsc
