default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DATABASE_POOL', 4) %>

development:
  <<: *default
  database: personal_development

test:
  <<: *default
  database: personal_test

production:
  <<: *default
  database: personal_production
