common: &default_settings
  license_key: '<%= ENV["NEW_RELIC_LICENSE_KEY"] %>'
  app_name: <%= ENV["NEW_RELIC_APP_NAME"] %>
  log_level: info

development:
  <<: *default_settings
  app_name: <%= ENV["NEW_RELIC_APP_NAME"] %> (Development)
  developer_mode: false

test:
  <<: *default_settings
  app_name: <%= ENV["NEW_RELIC_APP_NAME"] %> (Test)
  monitor_mode: false

production:
  <<: *default_settings
