- name: "OmniAI"
  icon: "fas fa-robot"
  description: "A Ruby client library for OpenAI, Mistral, Claude, Google and more."
  url: "https://github.com/ksylvest/omniai/"
- name: "VoyageAI"
  icon: "fas fa-compass"
  description: "A Ruby client for the voyage AI embeddings / rerank APIs."
  url: "https://github.com/ksylvest/voyageai/"
- name: "Analytic"
  icon: "fas fa-chart-line"
  description: "A Rails engine for running basic analytics."
  url: "https://github.com/ksylvest/analytic/"
- name: "Ra"
  icon: "fas fa-sun"
  description: "A Ruby ray tracer for rendering graphics."
  url: "https://github.com/ksylvest/ra/"
- name: "Tights"
  icon: "fas fa-brush"
  description: "A React component library for using Bulma."
  url: "https://github.com/ksylvest/tights/"
- name: "Rhino"
  icon: "fas fa-server"
  description: "A Ruby rack server built using sockets, threads and a CLI."
  url: "https://github.com/ksylvest/rhino/"
- name: "Specifier"
  icon: "fas fa-gavel"
  description: "A Ruby testing framework built for examples, contexts and a CLI."
  url: "https://github.com/ksylvest/specifier/"
- name: "Enigma"
  icon: "fas fa-key"
  description: "A Ruby enigma machine (rotors, reflectors, plugboard and all)."
  url: "https://github.com/ksylvest/enigma/"
- name: "GraphQL Sources"
  icon: "fas fa-database"
  description: "A collection of common GraphQL loaders for Ruby on Rails."
  url: "https://github.com/ksylvest/graphql-sources/"
- name: "React Active Storage"
  icon: "fas fa-upload"
  description: "A React hook for uploading files to Rails Active Storage."
  url: "https://github.com/ksylvest/react-activestorage/"
- name: "Bun CircleCI Orb"
  icon: "fas fa-hotdog"
  description: "A CircleCI orb for installing Bun for building and testing projects."
  url: "https://circleci.com/developer/orbs/orb/ksylvest/bun"
- name: "Deno CircleCI Orb"
  icon: "fas fa-dragon"
  description: "A CircleCI orb for installing Deno for building and testing projects."
  url: "https://circleci.com/developer/orbs/orb/ksylvest/deno"
- name: "Attached"
  icon: "fas fa-paperclip"
  description: "A Rails gem for uploading files to Amazon, Google or Rackspace."
  url: "https://ksylvest.github.io/attached/"
- name: "Formula"
  icon: "fas fa-flask"
  description: "A Rails gem for creating rich forms with minimal markup."
  url: "https://formula.ksylvest.com/"
- name: "Erroneous"
  icon: "fas fa-exclamation"
  description: "A Rails gem for converting errors to human readable forms."
  url: "https://ksylvest.github.io/erroneous/"
- name: "Identifier"
  icon: "fas fa-tags"
  description: "A Ruby gem for generating UUIDs and GUIDs cross platform."
  url: "https://ksylvest.github.io/identifier/"
- name: "Serializer"
  icon: "fas fa-cogs"
  description: "A Rails gem for serializing settings with types and defaults."
  url: "https://ksylvest.github.io/serializer/"
- name: "Reason"
  icon: "fas fa-filter"
  description: "An iOS and Mac pod that adds enumerables, parsing, and more."
  url: "https://github.com/ksylvest/reason"
- name: "Geography"
  icon: "fas fa-globe"
  description: "An iOS and Mac pod for listing countries and regions."
  url: "https://github.com/ksylvest/geography"
- name: "Encore"
  icon: "fas fa-random"
  description: "An iOS and Mac pod that eliminates duplicate for callbacks."
  url: "https://github.com/ksylvest/encore/"
- name: "Setup"
  icon: "fas fa-magic"
  description: "A Bash script for setting up development environments."
  url: "https://ksylvest.github.io/setup/"
- name: "jQuery Age"
  icon: "fas fa-clock"
  description: "A JS library for formatting and counting dates in a friendly form."
  url: "https://ksylvest.github.io/jquery-age/"
- name: "jQuery Carousel"
  icon: "fas fa-images"
  description: "A JS library for browsing images in a photo carousel."
  url: "https://ksylvest.github.io/jquery-carousel/"
- name: "jQuery Gridly"
  icon: "fas fa-th"
  description: "A JS library for reording and resizing of elements on a grid."
  url: "https://ksylvest.github.io/jquery-gridly/"
- name: "jQuery Growl"
  icon: "fas fa-comments"
  description: "A JS library that enables growl style notifications."
  url: "https://ksylvest.github.io/jquery-growl/"
- name: "jQuery Lighter"
  icon: "fas fa-fire"
  description: "A JS library for full screen image browsing and zooming."
  url: "https://ksylvest.github.io/jquery-lighter/"
- name: "jQuery Modal"
  icon: "fas fa-expand"
  description: "A JS library for scrollable and static modals."
  url: "https://ksylvest.github.io/jquery-modal/"
- name: "jQuery Observer"
  icon: "fas fa-eye"
  description: "A JS library for throttled observing of form changes."
  url: "https://ksylvest.github.io/jquery-observer/"
- name: "jQuery Spin"
  icon: "fas fa-spinner"
  description: "A JS library for generating imageless vector spinners."
  url: "https://ksylvest.github.io/jquery-spin/"
